### ISSUE TITLE
[Examples] Test FundMover example.

### ISSUE THREAD

**Issue by sungwook-moon** [amino-os/Amino.Run#780]
We have an example - FundMover - for testing TwoPCCoordinatorPolicy manually. Style format doesn't seem to be enforced. Test this app, confirm style format and Gradle restrictions are enforced and close this issue.

**Comment by Vishwa4jeet** [comment]
1. Formatting issue for all the apps have been addressed by this PR #786 .
2. Tested the app:
**NOTE:** Requires setting up MariaDB before running the app.
App run screenshot:
![image](https://user-images.githubusercontent.com/36434930/60179097-89dd0800-983a-11e9-9539-573a6edb1055.png)
3. Identified some changes in the Readme.md file, made those changes and raised PR #807 .

**Comment by Vishwa4jeet** [comment]
@sungwook-moon Do we mean enforcing the Java 1.6 version compatibility, when mentioning 'check Gradle restrictions are enforced' ?
