### ISSUE TITLE
[Examples] Test MinnieTwitter example.

### ISSUE THREAD

**Issue by sungwook-moon** [amino-os/Amino.Run#781]
MinnieTwitter under examples looks to be outdated. 

1) The indentation at MinnieTwitterMain is different for example. Confirm the style-format is enforced at build time.

2) There is much unused code such as:
```
List<User> users = new ArrayList<User>();
```

3) UserManager is using annotation instead of using a spec to configure which DM to use.

**Comment by Vishwa4jeet** [comment]
1. Part 1 of the above issue is already addressed by this PR #786 .
2. Part 2 has also been addressed by PR #785 .

@sungwook-moon I think this issue can now be closed.

**Comment by quinton-hoole** [comment]
Thanks @Vishwa4jeet . Agreed.  Closing.
