### ISSUE TITLE
Add "failing-test" label to support failing-test template

### ISSUE THREAD

**Issue by AmitRoushan** [amino-os/Amino.Run#814]
**What would you like to be added**:
"failing-test" label is missing which is required to support "failing-test" template

**Why this is needed**:
To support labelling in issue creation.

**Comment by AmitRoushan** [comment]
@quinton-hoole @VenuReddy2103 
We missed to create "failing-test" label before merging PR #813.

**Comment by quinton-hoole** [comment]
Thanks @AmitRoushan .  Done.
